/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DemoJDBC;

import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguyenthuyduong
 */
public class frmDanhSachSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form frmDanhSachSinhVien
     */
    public frmDanhSachSinhVien() {
        initComponents();
    }

    public void HienthiDSSV(){
        Connection cnn = CSDL.Database.KetnoiCSDL();
        if(cnn==null){
            JOptionPane.showMessageDialog(rootPane,"Loi ket noi CSDL");
            return;
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Ket noi CSDL thanh cong");
            String sql = "SELECT * FROM tbSinhvien";
            try{
                //thuc thi sql va lay ket qua
                PreparedStatement stm = cnn.prepareStatement(sql);
                //thuc hien lenh sql va luu ket qua vao resultset
                ResultSet rs = stm.executeQuery();
                DefaultTableModel dtm = (DefaultTableModel) tbSinhvien.getModel();
                //xoa du lieu neu co
                dtm.setRowCount(0);
                
                int dem =0;
                while(rs.next()){
                    String Masv = rs.getString("Masv");
                    String Hoten = rs.getString("Hoten");
                    String Dienthoai = rs.getString("Dienthoai");
                    dtm.addRow(new Object[]{Masv, Hoten, Dienthoai});
                    dem++;
                }
                if(dem==0){
                    JOptionPane.showMessageDialog(this,"Chua co du lieu");
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Loi truy van ");
                Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSinhvien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMasv = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtDienthoai = new javax.swing.JTextField();
        btnThemsinhvien = new javax.swing.JButton();
        btnSuasinhvien = new javax.swing.JButton();
        btnXoasinhvien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH SINH VIÊN");

        tbSinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SV", "Họ và tên", "Điện thoại"
            }
        ));
        tbSinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSinhvien);

        jLabel2.setText("Mã SV");

        jLabel3.setText("Họ và tên");

        jLabel4.setText("Điện thoại");

        btnThemsinhvien.setText("Thêm sinh viên");
        btnThemsinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemsinhvienActionPerformed(evt);
            }
        });

        btnSuasinhvien.setText("Sửa sinh viên");
        btnSuasinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuasinhvienActionPerformed(evt);
            }
        });

        btnXoasinhvien.setText("Xoá sinh viên");
        btnXoasinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoasinhvienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDienthoai, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .addComponent(txtHoten)
                                    .addComponent(txtMasv)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemsinhvien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSuasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoasinhvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemsinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoasinhvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuasinhvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:CSDL
        HienthiDSSV();
    }//GEN-LAST:event_formWindowOpened

    private void btnThemsinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemsinhvienActionPerformed
        // TODO add your handling code here:
        String Masv = this.txtMasv.getText();
        String Hoten = this.txtHoten.getText();
        String Dienthoai = this.txtDienthoai.getText();
        
        Connection cnn = CSDL.Database.KetnoiCSDL();
        if(cnn==null){
            JOptionPane.showMessageDialog(rootPane,"Loi ket noi CSDL");
            return;
        }
        String sql = "INSERT INTO tbSinhvien (Masv,Hoten,Dienthoai) VALUES(?,?,?)";
        try{
            //thuc thi sql va lay ket qua
            PreparedStatement stm = cnn.prepareStatement(sql);
            stm.setString(1, Masv);
            stm.setString(2, Hoten);
            stm.setString(3, Dienthoai);
            //thuc thi lenh insert, update, delete và tra ban ghi duoc them
            int n = stm.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(this,"Chua co du lieu");
                //goi lai ham de hien thi danh sach sinh vien moi
                HienthiDSSV();
            }
        }
        catch(SQLException e)
        {
                JOptionPane.showMessageDialog(this,"Loi truy van ");
                Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnThemsinhvienActionPerformed

    private void btnXoasinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoasinhvienActionPerformed
        // TODO add your handling code here:
        int i = tbSinhvien.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(this,"Ban chua chon sinh vien can xoa");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tbSinhvien.getModel();
        //lay du lieu tu dong i, cot 0 (ma sinh vien)
        String masv = (String)dtm.getValueAt(i, 0);
        int res = JOptionPane.showConfirmDialog(this,"Xoa sinh vien", "Chac chan xoa",JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION);{
            Connection cnn = CSDL.Database.KetnoiCSDL();
            if(cnn==null){
                JOptionPane.showMessageDialog(this,"Loi ket noi CSDL");
                return;
            }
            String sql = "DELETE FROM tbSinhvien WHERE masv = ?";
            try{
                PreparedStatement stm = cnn.prepareStatement(sql);
                stm.setString(1, masv);
                int n = stm.executeUpdate();
                if(n>0){
                    JOptionPane.showMessageDialog(this,"Xoa thanh cong");
                    HienthiDSSV();
                }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this,"Loi SQL!");
                Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(Level.SEVERE, null, e);
            }
            
        }
    }//GEN-LAST:event_btnXoasinhvienActionPerformed

    private void tbSinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSinhvienMouseClicked
        // TODO add your handling code here:
        int i = this.tbSinhvien.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel) this.tbSinhvien.getModel();
        String masv = (String)dtm.getValueAt(i, 0);
        String hoten = (String)dtm.getValueAt(i, 1);
        String dienthoai = (String)dtm.getValueAt(i, 2);
        this.txtMasv.setText(masv);
        this.txtHoten.setText(hoten);
        this.txtDienthoai.setText(dienthoai);
    }//GEN-LAST:event_tbSinhvienMouseClicked

    private void btnSuasinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuasinhvienActionPerformed
        // TODO add your handling code here:
        int i = this.tbSinhvien.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(this,"Ban chua chon sinh vien nao");
            HienthiDSSV();
        }
        DefaultTableModel dtm = (DefaultTableModel) tbSinhvien.getModel();
        String masv = (String)dtm.getValueAt(i,0);
        int res = JOptionPane.showConfirmDialog(this,"Ban chua chon sinh vien nao","Chac chan",JOptionPane.YES_NO_OPTION);
        if(res==JOptionPane.YES_OPTION);{
            Connection cnn = CSDL.Database.KetnoiCSDL();
            if(cnn==null){
                JOptionPane.showMessageDialog(this,"Loi ket noi CSDL");
                return;
            }
        String masvmoi = this.txtMasv.getText();
        String hotenmoi = this.txtHoten.getText();
        String dienthoaimoi = this.txtDienthoai.getText();
        String sql = "UPDATE tbSinhvien SET masv=?,hoten=?,dienthoai=? WHERE masv = ?";
        try{
            //thuc thi sql va lay ket qua
            PreparedStatement stm = cnn.prepareStatement(sql);
            stm.setString(1, masvmoi);
            stm.setString(2, hotenmoi);
            stm.setString(3, dienthoaimoi);
            stm.setString(4, masv);
            //thuc thi lenh insert, update, delete và tra ban ghi duoc them
            int n = stm.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(this,"Sua thanh cong");
                //goi lai ham de hien thi danh sach sinh vien moi
                HienthiDSSV();
            }
        }
        catch(SQLException e)
        {
                JOptionPane.showMessageDialog(this,"Loi truy van ");
                Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnSuasinhvienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDanhSachSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDanhSachSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuasinhvien;
    private javax.swing.JButton btnThemsinhvien;
    private javax.swing.JButton btnXoasinhvien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSinhvien;
    private javax.swing.JTextField txtDienthoai;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMasv;
    // End of variables declaration//GEN-END:variables
}
